development:
  sessions:
    default:
      database: test_devise_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: test_devise_test
      hosts:
        - localhost:27017
